/***** BEGIN LICENSE BLOCK *****

BSD License

Copyright (c) 2005-2012, NIF File Format Library and Tools
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
3. The name of the NIF File Format Library and Tools project may not be
   used to endorse or promote products derived from this software
   without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

***** END LICENCE BLOCK *****/

#ifndef __NS_BASE_H__
#define __NS_BASE_H__

#define APP "NifSkope"

#define STR_NOTHING "None"
#define STR_TS "Tangent space (binormal & tangent vectors)"
#define STR_V20000005 "20.0.0.5"

#define NF_VSEPARATOR "."
#define NF_V03030013 0x0303000D
#define NF_V20000005 0x14000005
#define NF_V10000100 0x0A000100
#define NF_V20020000 0x14020000
#define NF_V20010003 0x14010003
#define NF_V10010000 0x0A010000
#define NF_V10020000 0x0A020000
#define NF_V10000000 0x0A000000
#define NF_V20000004 0x14000004
#define NF_V20050000 0x14050000
#define NF_V20020007 0x14020007
#define NF_V04010018 0x04010012
#define NF_V04000000 0x04000000
#define NF_V04000002 0x04000002
#define NF_V04010012 0x0401000C
#define NF_V02000011 0x0200000b
#define NF_V20030006 0x14030006

#define NF_H1 "NetImmerse File Format, Version "
#define NF_H2 "Gamebryo File Format, Version "
#define KF_H1 ";Gamebryo KFM File Version 2.0.0.0b"
#define NF_V20000005_DEFAULT_UV 11
#define NF_V20000005_DEFAULT_UV2 11
#define NF_V03030013_DEF_CR1 "Numerical Design Limited, Chapel Hill, NC 27514"
#define NF_V03030013_DEF_CR2 "Copyright (c) 1996-2000"
#define NF_V03030013_DEF_CR3 "All Rights Reserved"

#define FMASK_BSA  "*.bsa"
#define FMASK_FRAG "*.frag"
#define FMASK_PROG "*.prog"
#define FMASK_VERT "*.vert"
#define FMASK_KF   "*.kf"
#define FMASK_KFA  "*.kfa"
#define FMASK_KF_A "*.kf(a)"
#define FMASK_KFM  "*.kfm"
#define FMASK_NIF  "*.nif"
#define FMASK_TGA  "*.tga"
#define FMASK_DDS  "*.dds"
#define FMASK_BMP  "*.bmp"
#define FMASK_PNG  "*.png"
#define FMASK_JPG  "*.jpg"
#define FMASK_NIFCACHE "*.nifcache"
#define FMASK_TEXCACHE "*.texcache"
#define FMASK_PCPATCH "*.pcpatch"
#define FMASK_JMI "*.jmi"

// XML attribute values
#define AV_ARG "ARG"
#define AV_TEMPLATE "TEMPLATE"
#define AV_SEMANTICDATA_TEXTCOORD "TEXCOORD"
#define AV_SEMANTICDATA_POSITION "POSITION"
#define AV_SEMANTICDATA_NORMAL "NORMAL"
#define AV_SEMANTICDATA_INDEX "INDEX"
#define AV_FLOAT32_3 "F_FLOAT32_3"
#define AV_MESHPRMITIVETYPE_TRIANGLES "MESH_PRIMITIVE_TRIANGLES"
// T_BSLIGHTINGSHADERPROPERTY, T_BSEFFECTSHADERPROPERTY
//   TA_SHADERFLAGS2
#define AV_VERTEX_ANIMATION 29
#define AV_DOUBLE_SIDED 4

// XML "tag" "tag add"
#define T_ATEXTURERENDERDATA "ATextureRenderData"
#define T_NIDATASTREAM "NiDataStream"
	#define TA_NIDS_USAGE "Usage"
	#define TA_NIDS_ACCESS "Access"
#define T_HEADER "Header"
	#define TA_HVERSION "Version"
	#define TA_HSTRING "Header String"
	#define TA_HUV "User Version"
	#define TA_HUV2	"User Version 2"
	#define TA_HCR "Copyright"
	#define TA_HBLOCKSNUM "Num Blocks"
	#define TA_HBLOCKTYPES "Block Types"
	#define TA_HBLOCTYPEIDX "Block Type Index"
	#define TA_HBLOCKSIZE "Block Size"
	#define TA_HBLOCKTYPESNUM "Num Block Types"
	#define TA_HSTRINGSNUM "Num Strings"
	#define TA_HSTRINGS "Strings"
	#define TA_HSTRINGMAXLEN "Max String Length"
#define T_FOOTER "Footer"
	#define TA_FROOTS "Roots"
	#define TA_FROOTSNUM "Num Roots"

#define T_NISOURCETEXTURE "NiSourceTexture"
#define T_NIIMAGE "NiImage"
#define T_NISTRINGEXTRADATA "NiStringExtraData"
#define T_CONTROLLERLINK "ControllerLink"
#define T_NIFLOATINTERPOLATOR "NiFloatInterpolator"
#define T_NIFLOATDATA "NiFloatData"
#define T_NITRISHAPEDATA "NiTriShapeData"
#define T_NITRISTRIPSDATA "NiTriStripsData"
#define T_NISKININSTANCE "NiSkinInstance"
#define T_NIGEOMMORPHERCONTROLLER "NiGeomMorpherController"
#define T_NIUVCONTROLLER "NiUVController"
#define T_NITRIBASEDGEOM "NiTriBasedGeom"
#define T_NIBINARYEXTRADATA "NiBinaryExtraData"
#define T_NISKINDATA "NiSkinData"
#define T_NISKINPARTITION "NiSkinPartition"
#define T_BSLIGHTINGSHADERPROPERTY "BSLightingShaderProperty"
#define T_BSEFFECTSHADERPROPERTY "BSEffectShaderProperty"
#define T_NIALPHAPROPERTY "NiAlphaProperty"
#define T_NIZBUFFERPROPERTY "NiZBufferProperty"
#define T_NITEXTURINGPROPERTY "NiTexturingProperty"
#define T_NITEXTUREPROPERTY "NiTextureProperty"
#define T_NIMATERIALPROPERTY "NiMaterialProperty"
#define T_NISPECULARPROPERTY "NiSpecularProperty"
#define T_NIWIREFRAMEPROPERTY "NiWireframeProperty"
#define T_NIVERTEXTCOLORPROPERTY "NiVertexColorProperty"
#define T_NISTENCILPROPERTY "NiStencilProperty"
#define T_BSSHADERLIGHTINGPROPERTY "BSShaderLightingProperty"
#define T_BSSHADERNOLIGHTINGPROPERTY "BSShaderNoLightingProperty"
#define T_BSSHADERPPLIGHINGPROPERTY "BSShaderPPLightingProperty"
#define T_NIFLIPCONTROLLER "NiFlipController"
#define T_NITEXTURETRANSFORMCONTROLLER "NiTextureTransformController"
#define T_NIALPHACONTROLLER "NiAlphaController"
#define T_NIMATERIALCOLORCONTROLLER "NiMaterialColorController"
#define T_BSSHADERTEXTURESET "BSShaderTextureSet"
#define T_SKYSHADERPROPERTY "SkyShaderProperty"
#define T_TILESHADERPROPERTY "TileShaderProperty"
#define T_LIGHTING30SHADERPROPERTY "Lighting30ShaderProperty"
#define T_NINODE "NiNode"
#define T_NITRISHAPE "NiTriShape"
#define T_NITRISTRIPS "NiTriStrips"
#define T_NICOLLISIONOBJECT "NiCollisionObject"
#define T_BHKRIGIDBODYT "bhkRigidBodyT"
#define T_BHKMOPPBVTREESHAPE "bhkMoppBvTreeShape"
#define T_BHKPACKEDNITRISTRIPSSHAPE "bhkPackedNiTriStripsShape"
#define T_HKPACKEDNITRISTRIPSDATA "hkPackedNiTriStripsData"
#define T_BHKNITRISTRIPSSHAPE "bhkNiTriStripsShape"
#define T_BHKRIGIDBODY "bhkRigidBody"
#define T_BHKCOLLISIONOBJECT "bhkCollisionObject"
#define T_BSXFLAGS "BSXFlags"
#define T_NIBILLBOARDNODE "NiBillboardNode"
#define T_NITIMECONTROLLER "NiTimeController"
#define T_BHKREFOBJECT "bhkRefObject"
#define T_BHKCONSTRAINT "bhkConstraint"
#define T_NISEQUENCE "NiSequence"
#define T_NIPIXELDATA "NiPixelData"
#define T_BHKCONVEXVERTICESSHAPE "bhkConvexVerticesShape"
#define T_BHKMALLEABLECONSTRAINT "bhkMalleableConstraint"
#define T_BHKRAGDOLLCONSTRAINT "bhkRagdollConstraint"
#define T_BHKLIMITEDHINGECONSTRAINT "bhkLimitedHingeConstraint"
#define T_BHKHINGECONSTRAINT "bhkHingeConstraint"
#define T_BHKPRISMATICCONSTRAINT "bhkPrismaticConstraint"
#define T_NIAVOBJECT "NiAVObject"
#define T_NIMULTITARGETTRANSFORMCONTROLLER "NiMultiTargetTransformController"
#define T_NICONTROLLERMANAGER "NiControllerManager"
#define T_NICONTROLLERSEQUENCE "NiControllerSequence"
#define T_NIKEYFRAMEDATA "NiKeyframeData"

// main tags: compounds
#define C_TEXDESC "TexDesc"

// tag <add
#define TA_FILENAME "File Name"
#define TA_STRINGDATA "String Data"
#define TA_NAME "Name"
#define TA_CONTROLLEDBLOCKS "Controlled Blocks"
#define TA_NODENAME "Node Name"
#define TA_NODENAMEOFFSET "Node Name Offset"
#define TA_STRINGPALETTE "String Palette"
#define TA_PALETTE "Palette"
#define TA_NUMVERTICES "Num Vertices"
#define TA_TEXTURESOURCE "Texture Source"
#define TA_INDEX "Index"
#define TA_STRING "String"
#define TA_MORPHS "Morphs"
#define TA_INTERPOLATOR "Interpolator"
#define TA_INTERPOLATORS "Interpolators"
#define TA_INTERPOLATORWEIGHTS "Interpolator Weights"
#define TA_DATA "Data"
#define TA_VECTORS "Vectors"
#define TA_UVGROUPS "UV Groups"
#define TA_NUMSUBMESHES "Num Submeshes"
#define TA_DATAS "Datas"
#define TA_PRIMITIVETYPE "Primitive Type"
#define TA_NUMREGIONS "Num Regions"
#define TA_REGIONS "Regions"
#define TA_STARTINDEX "Start Index"
#define TA_NUMINDICES "Num Indices"
#define TA_NUMCOMPONENTS "Num Components"
#define TA_COMPONENTFORMATS "Component Formats"
#define TA_PROPERTIES "Properties"
#define TA_SHADERFLAGS2 "Shader Flags 2"
#define TA_VERTICES "Vertices"
#define TA_NORMALS "Normals"
#define TA_VERTEXCOLORS "Vertex Colors"
#define TA_TANGENTS "Tangents"
#define TA_BINORMALS "Binormals"
#define TA_UVSETS "UV Sets"
#define TA_UVSETS2 "UV Sets 2"
#define TA_TRIANGLES "Triangles"
#define TA_POINTS "Points"
#define TA_EXTRADATALIST "Extra Data List"
#define TA_BINARYDATA "Binary Data"
#define TA_SKELETONROOT "Skeleton Root"
#define TA_BONES "Bones"
#define TA_BONELIST "Bone List"
#define TA_HASVERTEXWEIGHTS "Has Vertex Weights"
#define TA_SKINPARTITION "Skin Partition"
#define TA_SKINPARTITIONBLOCKS "Skin Partition Blocks"
#define TA_STRIPS "Strips"
#define TA_STRIPLENGTHS "Strip Lengths"
#define TA_FLAGS "Flags"
#define TA_THRESHOLD "Threshold"
#define TA_FUNCTION "Function"
#define TA_BASETEXTURE "Base Texture"
#define TA_DARKTEXTURE "Dark Texture"
#define TA_DETAILTEXTURE "Detail Texture"
#define TA_GLOSSTEXTURE "Gloss Texture"
#define TA_GLOWTEXTURE "Glow Texture"
#define TA_BUMPMAPTEXTURE "Bump Map Texture"
#define TA_DECAL0TEXTURE "Decal 0 Texture"
#define TA_DECAL1TEXTURE "Decal 1 Texture"
#define TA_DECAL2TEXTURE "Decal 2 Texture"
#define TA_DECAL3TEXTURE "Decal 3 Texture"
#define TA_SOURCE "Source"
#define TA_UVSET "UV Set"
#define TA_FILTERMODE "Filter Mode"
#define TA_CLAMPMODE "Clamp Mode"
#define TA_HASTEXTURETRANSFORM "Has Texture Transform"
#define TA_TRANSLATION "Translation"
#define TA_TILING "Tiling"
#define TA_WROTATION "W Rotation"
#define TA_CENTEROFFSET "Center Offset"
#define TA_DELTA "Delta"
#define TA_TEXTURESLOT "Texture Slot"
#define TA_SOURCES "Sources"
#define TA_IMAGES "Images"
#define TA_OPERATION "Operation"
#define TA_IMAGE "Image"
#define TA_ALPHA "Alpha"
#define TA_AMBIENTCOLOR "Ambient Color"
#define TA_DIFFUSECOLOR "Diffuse Color"
#define TA_SPECULARCOLOR "Specular Color"
#define TA_EMISSIVECOLOR "Emissive Color"
#define TA_GLOSSINESS "Glossiness"
#define TA_TARGETCOLOR "Target Color"
#define TA_VERTEXMODE "Vertex Mode"
#define TA_LIGHTINGMODE "Lighting Mode"
#define TA_DRAWMODE "Draw Mode"
#define TA_TEXTURESET "Texture Set"
#define TA_NUMTEXTURES "Num Textures"
#define TA_TEXTURES "Textures"
#define TA_SOURCETEXTURE "Source Texture"
#define TA_BODY "Body"
#define TA_ROTATION "Rotation"
#define TA_SHAPE "Shape"
#define TA_TRIANGLE "Triangle"
#define TA_NORMAL "Normal"
#define TA_STRIPSDATA "Strips Data"
#define TA_CHILDREN "Children"
#define TA_HASBASETEXTURE "Has Base Texture"
#define TA_PIXELLAYOUT "Pixel Layout"
#define TA_USEMIPMAPS "Use Mipmaps"
#define TA_ALPHAFORMAT "Alpha Format"
#define TA_UNKNOWNBYTE "Unknown Byte"
#define TA_UNKNOWNBYTE2 "Unknown Byte 2"
#define TA_USEEXTERNAL "Use External"
#define TA_EXTERNAL "External"
#define TA_HASVERTICES "Has Vertices"
#define TA_HASNORMALS "Has Normals"
#define TA_HASUV "Has UV"
#define TA_NUMUVSETS "Num UV Sets"
#define TA_NUMUVSETS2 "Num UV Sets 2"
#define TA_HASTRIANGLES "Has Triangles"
#define TA_NUMTRIANGLES "Num Triangles"
#define TA_NUMTRIANGLEPOINTS "Num Triangle Points"
#define TA_CENTER "Center"
#define TA_RADIUS "Radius"
#define TA_UNKNOWNSHORT2 "Unknown Short 2"
#define TA_NUMSTRIPS "Num Strips"
#define TA_HASPOINTS "Has Points"
#define TA_UNKNOWNFLOATS1 "Unknown Floats 1"
#define TA_UNKNOWNINTS1 "Unknown Ints 1"
#define TA_SCALE "Scale"
#define TA_NUMDATALAYERS "Num Data Layers"
#define TA_DATALAYERS "Data Layers"
#define TA_PARENT "Parent"
#define TA_UNKNOWNSHORT "Unknown Short"
#define TA_COLLISIONOBJECT "Collision Object"
#define TA_COLFILTER "Col Filter"
#define TA_INTEGERDATA "Integer Data"
#define TA_COLFILTERCOPY "Col Filter Copy"
#define TA_BILLBOARDMODE "Billboard Mode"
#define TA_STENCILENABLED "Stencil Enabled"
#define TA_FAILACTION "Fail Action"
#define TA_ZFAILACTION "Z Fail Action"
#define TA_PASSACTION "Pass Action"
#define TA_STENCILFUNCTION "Stencil Function"
#define TA_NUMSUBSHAPES "Num Sub Shapes"
#define TA_SUBSHAPES "Sub Shapes"
#define TA_MOPPDATASIZE "MOPP Data Size"
#define TA_MOPPDATA "MOPP Data"
#define TA_ORIGIN "Origin"
#define TA_NUMCHILDREN "Num Children"
#define TA_NUMPROPERTIES "Num Properties"
#define TA_NUMEXTRADATALIST "Num Extra Data List"
#define TA_NUMMODIFIERS "Num Modifiers"
#define TA_MODIFIERS "Modifiers"
#define TA_ENTITIES "Entities"
#define TA_TSPACEFLAG "TSpace Flag"
#define TA_TEXTURECOUNT "Texture Count"
#define TA_PS2K "PS2 K"
#define TA_UNKNOWN1 "Unknown1"
#define TA_HASDARKTEXTURE "Has Dark Texture"
#define TA_HASDETAILTEXTURE "Has Detail Texture"
#define TA_HASGLOWTEXTURE "Has Glow Texture"
#define TA_HASBUMPMAPTEXTURE "Has Bump Map Texture"
#define TA_BUMPMAPLUMASCALE "Bump Map Luma Scale"
#define TA_BUMPMAPLUMAOFFSET "Bump Map Luma Offset"
#define TA_BUMPMAPMATRIX "Bump Map Matrix"
#define TA_M11 "m11"
#define TA_M12 "m12"
#define TA_M21 "m21"
#define TA_M22 "m22"
#define TA_HASDECAL0TEXTURE "Has Decal 0 Texture"
#define TA_HASDECAL1TEXTURE "Has Decal 1 Texture"
#define TA_HASDECAL2TEXTURE "Has Decal 2 Texture"
#define TA_APPLYMODE "Apply Mode"
#define TA_PIXELDATA "Pixel Data"
#define TA_STARTTIME "Start Time"
#define TA_STOPTIME "Stop Time"
#define TA_NUMSOURCES "Num Sources"
#define TA_FREQUENCY "Frequency"
#define TA_NUMNORMALS "Num Normals"
#define TA_UNKNOWN6FLOATS "Unknown 6 Floats"
#define TA_TARGET "Target"
#define TA_RAGDOLL "Ragdoll"
#define TA_LIMITEDHINGE "Limited Hinge"
#define TA_HINGE "Hinge"
#define TA_PIVOTA "Pivot A"
#define TA_PIVOTB "Pivot B"
#define TA_AXLEA "Axle A"
#define TA_AXLEB "Axle B"
#define TA_PERP2AXLEINA2 "Perp2 Axle In A2"
#define TA_PERP2AXLEINB2 "Perp2 Axle In B2"
#define TA_PLANEA "Plane A"
#define TA_PLANEB "Plane B"
#define TA_TWISTA "Twist A"
#define TA_TWISTB "Twist B"
#define TA_LENGTH "Length"
#define TA_LAYER "Layer"
#define TA_MATERIAL "Material"
#define TA_UNKNOWNFLOATS "Unknown Floats"
#define TA_UNKNOWNFLOATS2 "Unknown Floats 2"
#define TA_TARGETNAME "Target Name"
#define TA_TEXTKEYSNAME "Text Keys Name"
#define TA_EXTRATARGETS "Extra Targets"
#define TA_OBJECTPALETTE "Object Palette"
#define TA_OBJS "Objs"
#define TA_NUMCONTROLLERSEQUENCES "Num Controller Sequences"
#define TA_CONTROLLERSEQUENCES "Controller Sequences"
#define TA_MANAGER "Manager"
#define TA_CONTROLLER "Controller"
#define TA_NEXTCONTROLLER "Next Controller"
#define TA_AVOBJECT "AV Object"
#define TA_ROTATIONTYPE "Rotation Type"
#define TA_NUMMIPMAPS "Num Mipmaps"
#define TA_MIPMAPS "Mipmaps"
#define TA_WIDTH "Width"
#define TA_HEIGHT "Height"
#define TA_BITSPERPIXEL "Bits Per Pixel"
#define TA_BYTESPERPIXEL "Bytes Per Pixel"
#define TA_PIXELFORMAT "Pixel Format"
#define TA_REDMASK "Red Mask"
#define TA_GREENMASK "Green Mask"
#define TA_BLUEMASK "Blue Mask"
#define TA_ALPHAMASK "Alpha Mask"
#define TA_CHANNEL "Channel"
#define TA_CHANNELS "Channels"
#define TA_TYPE "Type"
#define TA_BITSPERCHANNEL "Bits Per Channel"
#define TA_NUMENTRIES "Num Entries"
#define TA_R "r"
#define TA_G "g"
#define TA_B "b"
#define TA_A "a"
#define TA_UNKNOWN3BYTES "Unknown 3 Bytes"
#define TA_UNKNOWN8BYTES "Unknown 8 Bytes"
#define TA_UNKNOWNINT "Unknown Int"
#define TA_UNKNOWNINT2 "Unknown Int 2"
#define TA_UNKNOWNINT3 "Unknown Int 3"
#define TA_UNKNOWNINT4 "Unknown Int 4"
#define TA_UNKNOWNBYTE1 "Unknown Byte 1"
#define TA_CONVENTION "Convention"
#define TA_NUMFACES "Num Faces"
#define TA_OFFSET "Offset"
#define TA_NUMPIXELS "Num Pixels"

// NiBlocks - artificial blocks
#define B_NIHEADER "NiHeader"
#define B_NIFOOTER "NiFooter"
#define B_NIBLOCK "NiBlock"

// XML type names
#define TN_STRING "string"
#define TN_MESHPRIMITIVETYPE "MeshPrimitiveType"
#define TN_COMPONENTFORMAT "ComponentFormat"
#define TN_REF "Ref"
#define TN_PTR "Ptr"

// display names - column headers
#define DN_NAME "Name"
#define DN_TYPE "Type"
#define DN_VAL "Value"
#define DN_ARG "Argument"
#define DN_ARR1 "Array1"
#define DN_ARR2 "Array2"
#define DN_COND "Condition"
#define DN_VER1 "since"
#define DN_VER2 "until"
#define DN_VERCOND "Version Condition"

// texture names - inetrnal use
#define TX_BASE "base"
#define TX_DARK "dark"
#define TX_DETAIL "detail"
#define TX_GLOSS "gloss"
#define TX_GLOW "glow"
#define TX_BUMPMAP "bumpmap"
#define TX_DECAL0 "decal0"
#define TX_DECAL1 "decal1"
#define TX_DECAL2 "decal2"
#define TX_DECAL3 "decal3"

// blend function names
#define BF_ONE "One"
#define BF_ZERO "Zero"
#define BF_SRC_COLOR "Src Color"
#define BF_INV_SRC_COLOR "Inv Src Color"
#define BF_DST_COLOR "Dst Color"
#define BF_INV_DST_COLOR "Inv Dst Color"
#define BF_SRC_ALPHA "Src Alpha"
#define BF_INV_SRC_ALPHA "Inv Src Alpha"
#define BF_DST_ALPHA "Dst Alpha"
#define BF_INV_DST_ALPHA "Inv Dst Alpha"
#define BF_SRC_ALPHA_SATURATE "Src Alpha Saturate"
// blend compare function names
#define CF_ALWAYS "Always"
#define CF_LESS "Less"
#define CF_EQUAL "Equal"
#define CF_LESS_OR_EQUAL "Less or Equal"
#define CF_GREATER "Greater"
#define CF_NOT_EQUAL "Not Equal"
#define CF_GREATER_OR_EQUAL "Greater or Equal"
#define CF_NEVER "Never"

// decal modes
#define DM_REPLACE "Replace"
#define DM_DECAL "Decal"
#define DM_MODULATE "Modulate"
#define DM_HILIGHT "Hilight"
#define DM_HILIGHT2 "Hilight2"

#endif /* __NS_BASE_H__ */
